In [1]:
import pandas as pd


In [2]:
import numpy as np


In [4]:
df1 = ['a','d','e','t']
df1

['a', 'd', 'e', 't']

In [119]:
k = [1,2,3,4,5]
k

[1, 2, 3, 4, 5]

In [121]:
import pandas as pd

In [122]:
pd.Series(df1,k) # last object in the () comes first

NameError: name 'df1' is not defined

In [8]:
pd.Series(k,df1)

a    1
d    2
e    3
t    4
dtype: int64

In [11]:
np.random.rand(5,4)

array([[0.60557387, 0.27588407, 0.17704272, 0.19690405],
       [0.59248274, 0.39779939, 0.94477077, 0.48873187],
       [0.87943605, 0.74001793, 0.72021273, 0.54582654],
       [0.62511859, 0.29735287, 0.26261834, 0.16256385],
       [0.00377525, 0.48163172, 0.286006  , 0.0116941 ]])

In [13]:
pd.Series(k),np.random.rand(5,4)

(0    1
 1    2
 2    3
 3    4
 dtype: int64,
 array([[0.86127455, 0.98117039, 0.05446688, 0.05753937],
        [0.69588358, 0.42182686, 0.39824905, 0.1535296 ],
        [0.91233966, 0.39535282, 0.22336401, 0.29119585],
        [0.42424589, 0.74144113, 0.23058918, 0.68851592],
        [0.65161884, 0.68407056, 0.81135498, 0.49924915]]))

In [ ]:
n = [1,2]

In [126]:
c= pd.DataFrame(np.random.rand(5,4))
c

0         1         2         3
0  0.682574  0.658526  0.003179  0.607646
1  0.430108  0.823171  0.091775  0.757713
2  0.024848  0.330310  0.535049  0.006127
3  0.855929  0.500134  0.347806  0.486723
4  0.264632  0.624637  0.527361  0.241655

In [ ]:
## PANDAS......pandas are used for alphbetical things and numpy is used for numerical things
## pd.series is used for ......one dimensional data
## pd.DataFrame is used for ....two dimensional data

In [9]:
import pandas as pd

In [1]:
k = ('a','r','k','w')
k

('a', 'r', 'k', 'w')

In [12]:
list = [100,300,4,5]
list

[100, 300, 4, 5]

In [3]:
dict = {1:'k',2:'d',3:'ksj',7:'ram'}
dict

{1: 'k', 2: 'd', 3: 'ksj', 7: 'ram'}

In [20]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
arr

NameError: name 'np' is not defined

In [10]:
pd.Series(data=k)   #if u want to represent some names in list we use pandas

0    a
1    r
2    k
3    w
dtype: object

In [13]:
pd.Series(data=k, data = list) 

SyntaxError: keyword argument repeated (<ipython-input-13-8b8409ea24a5>, line 1)

In [14]:
pd.Series(k,list) 

100    a
300    r
4      k
5      w
dtype: object

In [15]:
pd.Series(list,k) 

a    100
r    300
k      4
w      5
dtype: int64

In [17]:
pd.Series(dict)

1      k
2      d
3    ksj
7    ram
dtype: object

In [3]:
import numpy as np

In [29]:
m = np.random.rand(5,5)
m

array([[0.693284  , 0.82280711, 0.73154511, 0.89326755, 0.28099942],
       [0.56614226, 0.87856726, 0.97649366, 0.15802549, 0.21032642],
       [0.36422498, 0.55072544, 0.23191649, 0.5221854 , 0.2893455 ],
       [0.42194994, 0.27466012, 0.14459481, 0.13945398, 0.6147315 ],
       [0.78711134, 0.59522488, 0.63356408, 0.26615875, 0.18664957]])

In [31]:
### DATA FRAMES AND INDEXING.......for 2D data analysis

In [5]:
import pandas as pd

In [6]:
K = pd.Series( [1,3,6,8,90],index =['KOTE','KAMESH','RAMESH','CHAMUDI','YUK'])
K 

KOTE        1
KAMESH      3
RAMESH      6
CHAMUDI     8
YUK        90
dtype: int64

In [7]:
n = pd.Series([4,6,2,5,6],index =['bindu','yuk','ramesh','CHAMUDI','KAMESH'])
n

bindu      4
yuk        6
ramesh     2
CHAMUDI    5
KAMESH     6
dtype: int64

In [9]:
K+n             ###  K AND n should have a same strings , otherwise its showa NaN

CHAMUDI    13.0
KAMESH      9.0
KOTE        NaN
RAMESH      NaN
YUK         NaN
bindu       NaN
ramesh      NaN
yuk         NaN
dtype: float64

In [10]:
n1 = pd.Series([4,6,2,5,6],index =['bindu','YUK','RAMESH','CHAMUDI','KAMESH'])  ##### inSeries 'S' should be capital
n1


bindu      4
YUK        6
RAMESH     2
CHAMUDI    5
KAMESH     6
dtype: int64

In [11]:
K+n1

CHAMUDI    13.0
KAMESH      9.0
KOTE        NaN
RAMESH      8.0
YUK        96.0
bindu       NaN
dtype: float64

In [13]:
E=np.random.rand(5,5)
E

array([[0.00413285, 0.79220345, 0.6366383 , 0.98459127, 0.6495708 ],
       [0.67376969, 0.14977916, 0.84805239, 0.66753403, 0.24075358],
       [0.88168236, 0.78382277, 0.96320412, 0.66658113, 0.0388438 ],
       [0.60984642, 0.25578336, 0.98077001, 0.08393491, 0.53887569],
       [0.4640338 , 0.14299485, 0.01958184, 0.02375479, 0.04678165]])

In [51]:
pd.DataFrame(E,index = ['A','B','C','D','E'])    #####  D & F should be a capital letter
                                                

0         1         2         3         4
A  0.004133  0.792203  0.636638  0.984591  0.649571
B  0.673770  0.149779  0.848052  0.667534  0.240754
C  0.881682  0.783823  0.963204  0.666581  0.038844
D  0.609846  0.255783  0.980770  0.083935  0.538876
E  0.464034  0.142995  0.019582  0.023755  0.046782

In [62]:
w = pd.DataFrame(np.random.rand(5,5), index = 'k a m e s'.split(), columns = 'kamesh bharath ramesh kotr hrc'.split())
w


kamesh   bharath    ramesh      kotr       hrc
k  0.778317  0.162427  0.799628  0.136700  0.056241
a  0.802435  0.172769  0.539133  0.191770  0.042565
m  0.804071  0.565659  0.690875  0.443725  0.832599
e  0.161172  0.051810  0.150716  0.402030  0.916867
s  0.308779  0.439457  0.103470  0.688205  0.143212

In [58]:
w = pd.DataFrame(np.random.rand(5,5), columns = 'kamesh bharath ramesh kotr hrc'.split())
w

kamesh   bharath    ramesh      kotr       hrc
0  0.472307  0.171472  0.497218  0.121213  0.872011
1  0.297609  0.125568  0.995788  0.668995  0.446087
2  0.705761  0.895009  0.544367  0.599451  0.058576
3  0.900675  0.200738  0.393049  0.091451  0.614917
4  0.708682  0.444777  0.688492  0.306168  0.091188

In [127]:
w = pd.DataFrame(np.random.rand(5,5),index = [2,3,4,5,6] ,columns = [1,2,3,4,5])
w

1         2         3         4         5
2  0.315424  0.982785  0.664988  0.464565  0.699273
3  0.596162  0.418794  0.242497  0.171273  0.372592
4  0.726986  0.780341  0.436201  0.148971  0.165533
5  0.803558  0.679339  0.849833  0.530879  0.114915
6  0.677862  0.215031  0.545408  0.815145  0.827028

In [130]:
w = pd.DataFrame(np.random.rand(5,5),index = [2,3,4,5,6] ,columns ='kamesh bharath ramesh kotr hrc'.split())  ## column names changed to names
w

kamesh   bharath    ramesh      kotr       hrc
2  0.366439  0.764385  0.216006  0.190968  0.147707
3  0.390747  0.148487  0.415599  0.947320  0.843754
4  0.552110  0.273116  0.555436  0.417561  0.217072
5  0.432439  0.665266  0.395193  0.294669  0.151375
6  0.218308  0.218372  0.409637  0.297743  0.225917

In [65]:
w['kamesh']

2    0.437184
3    0.135099
4    0.625546
5    0.629043
6    0.424740
Name: kamesh, dtype: float64

In [68]:
w['bindusai'] = w['kamesh'] + w['bharath']     ## column operations(add of extra column)
w


kamesh   bharath    ramesh      kotr       hrc  bindusai
2  0.437184  0.527609  0.168406  0.897365  0.295030  0.964793
3  0.135099  0.448169  0.559726  0.062742  0.685982  0.583267
4  0.625546  0.399815  0.814859  0.852831  0.900571  1.025361
5  0.629043  0.912978  0.612228  0.205247  0.333998  1.542021
6  0.424740  0.506945  0.264530  0.390685  0.979554  0.931685

In [71]:
w['100'] = w['kamesh'] + w['bharath']     ## column operations(add of extra column)
w

kamesh   bharath    ramesh      kotr       hrc  bindusai       100
2  0.437184  0.527609  0.168406  0.897365  0.295030  0.964793  0.964793
3  0.135099  0.448169  0.559726  0.062742  0.685982  0.583267  0.583267
4  0.625546  0.399815  0.814859  0.852831  0.900571  1.025361  1.025361
5  0.629043  0.912978  0.612228  0.205247  0.333998  1.542021  1.542021
6  0.424740  0.506945  0.264530  0.390685  0.979554  0.931685  0.931685

In [84]:
w.drop('100', axis = 1)  # droping column '100'


kamesh   bharath    ramesh      kotr       hrc  bindusai
2  0.437184  0.527609  0.168406  0.897365  0.295030  0.964793
3  0.135099  0.448169  0.559726  0.062742  0.685982  0.583267
4  0.625546  0.399815  0.814859  0.852831  0.900571  1.025361
5  0.629043  0.912978  0.612228  0.205247  0.333998  1.542021
6  0.424740  0.506945  0.264530  0.390685  0.979554  0.931685

In [83]:
w.drop(6)   ## dropping row '6'

kamesh   bharath    ramesh      kotr       hrc  bindusai       100
2  0.437184  0.527609  0.168406  0.897365  0.295030  0.964793  0.964793
3  0.135099  0.448169  0.559726  0.062742  0.685982  0.583267  0.583267
4  0.625546  0.399815  0.814859  0.852831  0.900571  1.025361  1.025361
5  0.629043  0.912978  0.612228  0.205247  0.333998  1.542021  1.542021

In [87]:
import pandas as pd

In [97]:
list = ['kamesh','bharath','rahul','thilak']
list

['kamesh', 'bharath', 'rahul', 'thilak']

In [105]:
df =pd.DataFrame({'name': list,'mat':[90,23,57,56],'phy' : [23,89,66,88],'chem' : [33,34,99,100], })
df

name  mat  phy  chem
0   kamesh   90   23    33
1  bharath   23   89    34
2    rahul   57   66    99
3   thilak   56   88   100

In [106]:
df =pd.DataFrame({'name': list,'mat':[90,23,57,56],'phy' : [23,89,66,88],'chem' : [33,34,99,100], },index = [40,50,56,78])
df

name  mat  phy  chem
40   kamesh   90   23    33
50  bharath   23   89    34
56    rahul   57   66    99
78   thilak   56   88   100

In [110]:
df["total"] = df["mat"]+df["phy"]+df["chem"]
df

name  mat  phy  chem  total
40   kamesh   90   23    33    146
50  bharath   23   89    34    146
56    rahul   57   66    99    222
78   thilak   56   88   100    244

In [114]:
df['percentage'] = df['total']/300 *100
df

name  mat  phy  chem  total  percentage
40   kamesh   90   23    33    146   48.666667
50  bharath   23   89    34    146   48.666667
56    rahul   57   66    99    222   74.000000
78   thilak   56   88   100    244   81.333333

In [ ]:
##### assesment

In [132]:
import numpy as np

In [138]:
np.zeros(10 ,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [163]:
c=np.zeros(10 ,dtype = int)
c[4]=1
c

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
import numpy as np

In [144]:
arr = np.arrange(10,45)            ### 'arrange' is coorect to.....'arange'
arr

AttributeError: module 'numpy' has no attribute 'arrange'

In [150]:
arr = np.arange(10,65)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64])

In [161]:
arr =np.arange(65,9,-1)
arr

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [162]:
arr[ ::-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [156]:
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])