In [1]:
import pandas as pd


In [2]:
import numpy as np


In [4]:
df1 = ['a','d','e','t']
df1

['a', 'd', 'e', 't']

In [6]:
k = [1,2,3,4]

In [7]:
pd.Series(df1,k) # last object in the () comes first

1    a
2    d
3    e
4    t
dtype: object

In [8]:
pd.Series(k,df1)

a    1
d    2
e    3
t    4
dtype: int64

In [11]:
np.random.rand(5,4)

array([[0.60557387, 0.27588407, 0.17704272, 0.19690405],
       [0.59248274, 0.39779939, 0.94477077, 0.48873187],
       [0.87943605, 0.74001793, 0.72021273, 0.54582654],
       [0.62511859, 0.29735287, 0.26261834, 0.16256385],
       [0.00377525, 0.48163172, 0.286006  , 0.0116941 ]])

In [13]:
pd.Series(k),np.random.rand(5,4)

(0    1
 1    2
 2    3
 3    4
 dtype: int64,
 array([[0.86127455, 0.98117039, 0.05446688, 0.05753937],
        [0.69588358, 0.42182686, 0.39824905, 0.1535296 ],
        [0.91233966, 0.39535282, 0.22336401, 0.29119585],
        [0.42424589, 0.74144113, 0.23058918, 0.68851592],
        [0.65161884, 0.68407056, 0.81135498, 0.49924915]]))

In [ ]:
# PANDAS......pandas are used for alphbetical things and numpy is used for numerical things

In [9]:
import pandas as pd

In [1]:
k = ('a','r','k','w')
k

('a', 'r', 'k', 'w')

In [12]:
list = [100,300,4,5]
list

[100, 300, 4, 5]

In [3]:
dict = {1:'k',2:'d',3:'ksj',7:'ram'}
dict

{1: 'k', 2: 'd', 3: 'ksj', 7: 'ram'}

In [20]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
arr

NameError: name 'np' is not defined

In [10]:
pd.Series(data=k)   #if u want to represent some names in list we use pandas

0    a
1    r
2    k
3    w
dtype: object

In [13]:
pd.Series(data=k, data = list) 

SyntaxError: keyword argument repeated (<ipython-input-13-8b8409ea24a5>, line 1)

In [14]:
pd.Series(k,list) 

100    a
300    r
4      k
5      w
dtype: object

In [15]:
pd.Series(list,k) 

a    100
r    300
k      4
w      5
dtype: int64

In [17]:
pd.Series(dict)

1      k
2      d
3    ksj
7    ram
dtype: object

In [23]:
import numpy as np

In [29]:
m = np.random.rand(5,5)
m

array([[0.693284  , 0.82280711, 0.73154511, 0.89326755, 0.28099942],
       [0.56614226, 0.87856726, 0.97649366, 0.15802549, 0.21032642],
       [0.36422498, 0.55072544, 0.23191649, 0.5221854 , 0.2893455 ],
       [0.42194994, 0.27466012, 0.14459481, 0.13945398, 0.6147315 ],
       [0.78711134, 0.59522488, 0.63356408, 0.26615875, 0.18664957]])

In [31]:
### DATA FRAMES AND INDEXING

In [38]:
K = pd.Series( [1,3,6,8,90],index =['KOTE','KAMESH','RAMESH','CHAMUDI','YUK'])
K 

KOTE        1
KAMESH      3
RAMESH      6
CHAMUDI     8
YUK        90
dtype: int64

In [43]:
n = pd.Series([4,6,2,5,6],index =['bindu','YUK','RAMESH','CHAMUDI','KAMESH'])
n

bindu      4
YUK        6
RAMESH     2
CHAMUDI    5
KAMESH     6
dtype: int64

In [42]:
k+n

TypeError: Cannot broadcast np.ndarray with operand of type <class 'tuple'>